version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"   # main gateway for all services
      - "4571:4571"
    environment:
      - SERVICES=s3,iam,lambda,cloudformation,ec2,sts
      - DATA_DIR=/var/lib/localstack/data
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
